[formatter.nix]
command = "nixfmt"
options = ["--"]
includes = ["*.nix"]

[formatter.toml]
command = "taplo"
options = ["format", "--"]
includes = ["*.toml"]

[formatter.markdown]
command = "prettier"
options = ["--parser", "markdown", "--write", "--"]
includes = ["*.md"]
